/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ticket.system;

import ticket.system.Services.UserBookingServices;
import ticket.system.entities.Ticket;
import ticket.system.entities.User;
import ticket.system.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {


    public static void main(String[] args) {
        System.out.println("Train Booking System");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingServices userBookingServices;
        try {
            userBookingServices = new UserBookingServices();
        } catch (IOException ex) {
            System.out.println("There is something Wrong");
            return;

        }
        while (option != 7) {
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Train");
            System.out.println("5. Book a Seats");
            System.out.println("6.Cancel My Booking");
            System.out.println("Exit the Application");
            option = sc.nextInt();
            switch (option) {
                case 1:
                    System.out.println("Enter userName to signup");
                    String nameToSignup = sc.next();
                    System.out.println("Enter your Password");
                    String passwordToSignup = sc.next();
                    User userToSIgnup = new User(nameToSignup, passwordToSignup, UserServiceUtil.hashPassword(passwordToSignup), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingServices.signUp(userToSIgnup);
                    break;
                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = sc.next();
                    System.out.println("Enter the password");
                    String passwordToLogin = sc.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingServices = new UserBookingServices(userToLogin)
                    } catch (IOException ex) {
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching yout Booking");
                    userBookingServices.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your Source Station");
                    String source = sc.next();
                    System.out.println("Type your Destination Station");
                    String dest = sc.next();


            }
        }
    }
}
